ALTER TABLE matches ALTER COLUMN file_hash TYPE VARCHAR(255);
ALTER TABLE matches ALTER COLUMN match_signature TYPE TEXT;

ALTER TABLE player_results ALTER COLUMN player_name TYPE VARCHAR(255);
ALTER TABLE player_results ALTER COLUMN champion TYPE VARCHAR(255);

ALTER TABLE players ALTER COLUMN name TYPE VARCHAR(255);